/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_byk_pandora_bsdiff_BsDifferUtil */

#ifndef _Included_cn_byk_pandora_bsdiff_BsDifferUtil
#define _Included_cn_byk_pandora_bsdiff_BsDifferUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_byk_pandora_bsdiff_BsDifferUtil
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_byk_pandora_bsdiff_BsDifferUtil_run
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
