/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_byk_pandora_bsdiffer_BsDiffer */

#ifndef _Included_cn_byk_pandora_bsdiffer_BsDiffer
#define _Included_cn_byk_pandora_bsdiffer_BsDiffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_byk_pandora_bsdiffer_BsDiffer
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_byk_pandora_bsdiffer_BsDiffer_run
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
